filter:
    excluded_paths:
        - 'vendor/*'
        - 'tests/*'
        - 'examples/*'
    paths: {  }
tools:
    sensiolabs_security_checker: true
    external_code_coverage: true
    php_cs_fixer:
        config: { level: psr2 }
    php_analyzer:
        enabled: true
        extensions:
            - php
        dependency_paths: {  }
        filter:
            excluded_paths:
                - 'vendor/*'
                - 'tests/*'
                - 'examples/*'
            paths: {  }
        path_configs: {  }
    php_sim:
        enabled: true
        min_mass: 16
        filter:
            excluded_paths:
                - 'vendor/*'
                - 'tests/*'
                - 'examples/*'
            paths: {  }
    php_pdepend:
        enabled: true
        configuration_file: null
        suffixes:
            - php
        excluded_dirs: {  }
        filter:
            excluded_paths:
                - 'vendor/*'
                - 'tests/*'
                - 'examples/*'
            paths: {  }
    php_code_sniffer:
        config:
            standard: "PSR2"
    php_mess_detector:
        enabled: true
        filter:
            excluded_paths:
                - 'vendor/*'
                - 'tests/*'
                - 'examples/*'
            paths: {  }
